### ISSUE TITLE
How can i get print job id after send a job?

### ISSUE THREAD

**Issue by thuongqbd** [rawilk/laravel-printing#1]
### Description
After send a job, how can i get print job id from print node?

### Steps to reproduce
`Printing::newPrintTask()
    ->printer($printerId)
    ->file('path_to_file.pdf')
    ->send();`

**Context**
- Laravel Printing version: 1.1.3
- Laravel version:  7.x

**Comment by rawilk** [comment]
When `send()` is called, it returns an instance of `PrintJob`, which has a method `id` on it.

```php
$printJob = Printing::newPrintTask()
    ->printer($printerId)
    ->file('path_to_file.pdf')
    ->send();

dd($printJob->id());
```

**Note:** This is untested and I can't guarantee that it works at this time.

**Comment by thuongqbd** [comment]
I tested `$printJob->id()`, it return null

**Comment by rawilk** [comment]
I do receive the print job ID from PrintNode when a successful response is returned, so it should be just a matter of me setting the id property on the print job instance itself I return it. I'll just update that when I get a chance to.
