### ISSUE TITLE
Question: HTTP Error (400): 'offset' not supported

### ISSUE THREAD

**Issue by mainul2k2** [rawilk/laravel-printing#10]
HI,
Thanks for the awesome plugin.

i am using below two lines to return all printers in my controller file.

$printers = Printing::printers();
return $printers;

It does not show anything.

Then i find rawlink/laravel-printing/src/printing.php file where i pass the $e. Then i get the error [{"statusCode":"400","message":"HTTP Error (400): 'offset' not supported"}]

    public function printers(): Collection
    {
        try {
            $printers = $this->driver->printers();
        } catch (\Throwable $e) {
            $printers = collect([$e]);
        }
        $this->resetDriver();
        return $printers;
    }

Am i doing something wrong?

**Comment by flexchar** [comment]
Same here. I installed and was presented with an empty list. I dived deep and reached PrintNode\Client. It is the source of bug. I'll see if I can come up with something meaningful.

**Comment by mainul2k2** [comment]
@flexchar Thanks bro, perfectly working

> Same here. I installed and was presented with an empty list. I dived deep and reached PrintNode\Client. It is the source of bug. I'll see if I can come up with something meaningful.
> 
> ~It seems like there is a pull-request fixing this issue back in 2017. Honestly it strikes me hard how the package of a commercial product is this abandoned. [PrintNode/PrintNode-PHP#20](https://github.com/PrintNode/PrintNode-PHP/pull/20)~
> 
> Turns out they changed API for newly created users to use different offset string and thus why the issue arose. I created simple pull that fixes [PrintNode/PrintNode-PHP#41](https://github.com/PrintNode/PrintNode-PHP/pull/41). I also contacted them - they're planning on refreshing client libraries later this year.

**Comment by tkrause** [comment]
So I'm having this same issue with the latest 1.3 version of this package.

Looking more into it, PrintNode patched this in dev-master but did not tag it. When trying to require dev-master, it doesn't work due to being locked to rc1.
