### ISSUE TITLE
Can't use Guzzle when install library

### ISSUE THREAD

**Issue by stzoran1** [rawilk/laravel-printing#11]
### Steps to reproduce
After installing library can't use Guzzle for making requests

**Context**
-Laravel 8
-PHP 7.4
-Windows 10 64bit

Error I am getting:

`{
    "message": "Interface 'Psr\\Http\\Client\\ClientInterface' not found",
    "exception": "Error",
    "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\guzzlehttp\\guzzle\\src\\Client.php",
    "line": 17,
    "trace": [
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\composer\\ClassLoader.php",
            "line": 444,
            "function": "include"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\composer\\ClassLoader.php",
            "line": 322,
            "function": "Composer\\Autoload\\includeFile"
        },
        {
            "function": "loadClass",
            "class": "Composer\\Autoload\\ClassLoader",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Client\\PendingRequest.php",
            "line": 639,
            "function": "spl_autoload_call"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Client\\PendingRequest.php",
            "line": 573,
            "function": "buildClient",
            "class": "Illuminate\\Http\\Client\\PendingRequest",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\helpers.php",
            "line": 234,
            "function": "Illuminate\\Http\\Client\\{closure}",
            "class": "Illuminate\\Http\\Client\\PendingRequest",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Client\\PendingRequest.php",
            "line": 589,
            "function": "retry"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Client\\PendingRequest.php",
            "line": 493,
            "function": "send",
            "class": "Illuminate\\Http\\Client\\PendingRequest",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\app\\DistOne\\DistOneApiClient.php",
            "line": 132,
            "function": "post",
            "class": "Illuminate\\Http\\Client\\PendingRequest",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\app\\DistOne\\DistOneApiClient.php",
            "line": 80,
            "function": "readData",
            "class": "App\\DistOne\\DistOneApiClient",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\app\\Http\\Controllers\\OrdersController.php",
            "line": 49,
            "function": "getOrders",
            "class": "App\\DistOne\\DistOneApiClient",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php",
            "line": 54,
            "function": "ajaxOrders",
            "class": "App\\Http\\Controllers\\OrdersController",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
            "line": 254,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
            "line": 197,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 692,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\app\\Http\\Middleware\\CheckRole.php",
            "line": 22,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "App\\Http\\Middleware\\CheckRole",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\app\\Http\\Middleware\\LogoutIfNotActive.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "App\\Http\\Middleware\\LogoutIfNotActive",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php",
            "line": 41,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php",
            "line": 78,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\AuthenticateSession.php",
            "line": 58,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\AuthenticateSession",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php",
            "line": 44,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Auth\\Middleware\\Authenticate",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php",
            "line": 49,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\View\\Middleware\\ShareErrorsFromSession",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php",
            "line": 121,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php",
            "line": 63,
            "function": "handleStatefulRequest",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php",
            "line": 37,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php",
            "line": 67,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 694,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 669,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 635,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 624,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 166,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php",
            "line": 86,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php",
            "line": 37,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fruitcake\\Cors\\HandleCors",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\fideloper\\proxy\\src\\TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 141,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 110,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\public\\index.php",
            "line": 52,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "E:\\projekti\\Lee Distributors\\orders-tracking\\server.php",
            "line": 21,
            "function": "require_once"
        }
    ]
}`

**Comment by ragingdave** [comment]
@rawilk I just hit this same error just even on installing the package. I'm on v1.3 (because I can't upgrade to PHP8 right now), laravel version 8.35.1 on linux. Installing this package effectively nukes the ability to use the Http package or guzzle even directly.

Any chance you've been able to take a look into fixing this?

**Comment by ragingdave** [comment]
@rawilk in fact it seems to prevent using the cups driver at all in v1.3. So that's a pretty breaking bug.

**Comment by mnwalker** [comment]
Getting same when using Laravel 8, tested PHP7.2, 7.4, 8.0

With LaravelPrinting enabled Guzzle crashed, remove LaravelPrinting and all works.

I noticed that installing this package removed "psr/http-client"
Manually adding this back into composer reinstalled fine and fixed the issue.
If no side effects on other dependencies then maybe worth adding as a dependency of this package to solve this.

**Comment by rawilk** [comment]
Closing this as it shouldn't be an issue with v2. Feel free to PR a fix for v1.x if you're still not able to upgrade.
