### ISSUE TITLE
No printer on localhost

### ISSUE THREAD

**Issue by omaisali** [rawilk/laravel-printing#13]
I have installed the package and Printnode. Set the api but when i do 

`print_r(Printing::printers());`

Array is empty

Any hint please? Thanks

**Comment by shubhamMazire1** [comment]
I am also getting this error
Array is empty
   ```
 $printers = Printing::defaultPrinterId();
        dd($printers);
```
please help us. @rawilk

**Comment by JonoHall** [comment]
+1 here. 

This bit of code produces an empty list:

```
$printers = Printing::printers();
dd($printers);
````

Result:

```
Illuminate\Support\Collection {#1349 ▼
  #items: []
}
```

But I can print if I specifically select a printer, so I know the API requests are working.

**Comment by JonoHall** [comment]
OK, worked it out. 

This package is requiring an out of date printnode package which relies on "offset" in the API which is breaking on new accounts. "offset" was replaced with "after" in subsequent updates of the printnode-php package, but the required version isn't being updated.

In any case, in your composer.json replace:
"printnode/printnode-php": "^2.0@RC"

With:
"printnode/printnode-php": "master"

Obviously you might want to be a bit more strict on your version than just "master", but that's as far as my knowledge on the matter can help.

**Comment by shamsuljewel** [comment]
@JonoHall I have tried that also, but still does not getting any printers.

**Comment by rawilk** [comment]
I plan on making some updates to how the PrintNode driver works behind the scenes which will hopefully help resolve this for people that have this issue.

**Comment by Sakthivel2001-dev** [comment]
I am using php version 7.4 what can I do. I cannot update the package version to v3.0.0

**Comment by Oscar-PF** [comment]
I have the same problem but I'm using cups, not PrintNode. Any suggestions?. Thanks in advance
