### ISSUE TITLE
Feature Request: Add ability to access driver directly

### ISSUE THREAD

**Issue by tkrause** [rawilk/laravel-printing#15]
From what I can tell right now, it doesn't look like you can directly access the driver and thus the client under it for something like PrintNode. 

Their API contains a number of helpful routes like whoami, computers, and more that would be nice to access from the library without using PrintNode directly.

**Comment by rawilk** [comment]
I personally have no need/interest for adding something like this to the repository. Feel free to fork/extend your own version to get desired functionality.
