### ISSUE TITLE
Cups Printing::find broken when invalid id is passed

### ISSUE THREAD

**Issue by ragingdave** [rawilk/laravel-printing#17]
### Description
Using Cups on v1.3, when calling Printing::find on an invalid ID, results in a Rawilk\Printing\Drivers\Cups\Entity\Printer instance, but for a random printer. This means that there's really no way to confirm that the printer being looked up is the right one.

### Steps to reproduce
Having a working CUPS server with printers configured. Call Printing::find('invalid'), and see that you still get a printer instance.

When dumping the Entity, you can see in the ResponseParser the following:
```
#responseParser: Smalot\Cups\Transport\ResponseParser^ {#5518
      #content: "\x01\x01\x04\x06\x00\x00\x00\x04\x01G\x00\x12attributes-charset\x00\x08us-asciiH\x00\eattributes-natural-language\x00\x05en-usA\x00\x0Estatus-message\x00#The printer or class was not found.\x03"
```
So there is already the knowlege that it wasn't found, but the package isn't validating anything in this case.

**Context**
- Laravel Printing version: 1.3.0
- Laravel version: 8.35.1

**Comment by rawilk** [comment]
It's been a while since I've looked at the CUPS driver, but I'm not really sure how something like that could be validated. Feel free to PR if you know of a way.
