### ISSUE TITLE
Unable to list printers on PrintNode due to offset not supported

### ISSUE THREAD

**Issue by tkrause** [rawilk/laravel-printing#18]
### Description

List printers with PrintNode. 

```php
$printers = Printing::printers()
```

Nothing is returned. After further investigation, PrintNode 2.0@RC1 is very old 2015 and does not match their API anymore.

dev-master is up to date as they have not tagged a new release as far as I can tell.

This occurs in all versions

**Comment by ledtest** [comment]
we can not get a correct response due to we use a free printnode account

**Comment by rawilk** [comment]
I plan on updating how the PrintNode driver works. I'm not sure if I'll need to write my own API wrapper or if there is already an alternative one made but it's clear that the package supposedly made by PrintNode is not maintained anymore so I can't really rely on it to work.

**Comment by rawilk** [comment]
In `v3.0.0`, you shouldn't run into this issue any more, as I've removed the `printnode/printnode-php` dependency entirely and wrote my own api wrapper for it.

Feel free to re-open if issue still persists and you're sure you have everything on your printnode account configured correctly.
