### ISSUE TITLE
Can't use contentType pdf_base64 with Printnode

### ISSUE THREAD

**Issue by krizzdev** [rawilk/laravel-printing#22]
### Description
Currently I can see no way of using the ContentType pdf_base64 for Printnode via the content() method.

```php
public function content($content): self
    {
        $this->job->content = base64_encode($content);
        $this->job->contentType = ContentType::RAW_BASE64;

        return $this;
    }
```
RAW_BASE64 is hardcoded in the content() method.

For CUPS there is a additional $contentType parameter for the content() method.

```php
public function content($content, string $contentType = ContentType::PDF): self
```

It would be great if this parameter can be added to the printnode drivers PrintTask class, too.

I can add a Pull Request, if mandatory.

Kind Regards
Christian

**Comment by rawilk** [comment]
@krizzdev I've merged a PR just now that adds support for this. Sorry for not getting to this until now.
