### ISSUE TITLE
installation problem 

### ISSUE THREAD

**Issue by khubaibfarooq** [rawilk/laravel-printing#26]
### how to use this

$printJob = Printing::newPrintTask()
    ->printer($printerId)
    ->file('path_to_file.pdf')
    ->send();

$printJob->id();
in class how to access printing class

**Comment by khubaibfarooq** [comment]
Class 'App\Http\Controllers\Printing' not found

**Comment by serdud** [comment]
`use Rawilk\Printing\Printing`
-_-
