### ISSUE TITLE
Error with guzzle after installing the laravel-printing

### ISSUE THREAD

**Issue by stefanotombari** [rawilk/laravel-printing#28]
### Description
I've installed laravel-printing using composer. In my application i use GuzzleHttp\Client, but after the installation i get back this error when i'm using it. 

Error
Interface 'Psr\Http\Client\ClientInterface' not found

If i remove laravel-printing, it works fine. 

**Context**
- Laravel Printing version: [1.3]
- Laravel version: [7.29.2]

**Comment by rawilk** [comment]
Not an issue with v2. Feel free to PR a fix to v1.x if needed.
