### ISSUE TITLE
CUPS Printer driver unable to print

### ISSUE THREAD

**Issue by rezuankassim** [rawilk/laravel-printing#3]
### Description
Unable to print via CUPS driver, getting 'A non-numeric value encountered'

```
$printers = Printing::printers();

Printing::newPrintTask()
    ->file(public_path('sample.pdf'))
    ->printer($printers->first()->id())
    ->send();
```

<img width="1249" alt="Screenshot 2020-09-04 at 5 39 40 PM" src="https://user-images.githubusercontent.com/53212160/92225379-b6c48a80-eed5-11ea-9861-aadf3aef38b8.png">

<img width="1239" alt="Screenshot 2020-09-04 at 5 42 21 PM" src="https://user-images.githubusercontent.com/53212160/92225623-0f942300-eed6-11ea-86ce-be834d51c335.png">

### Steps to reproduce
1. Used CUPS driver to print

**Context**
- Laravel Printing version: 1.2.0
- Laravel version: 7.27.0

**Comment by rawilk** [comment]
Thanks for taking the time to bring this issue to my attention. I have been able to replicate the issue on my end, so I will see if there's anything I can update in the package to make it work.

**Comment by rawilk** [comment]
Version 1.2.1 should fix this issue. The library I use to send the jobs to a CUPS print server requires a page range to be set. I was setting it to "1-" if a range has not been specified already to signify printing the entire document, but the library won't accept that. I've changed it to print pages "1-999", which should be more than enough in the majority of cases. 

If you somehow have a document more than 999 pages to be printed, make sure you specify the needed page range via the `range` function when creating a new print task.

See https://github.com/smalot/cups-ipp/issues/7 for more information.
