### ISSUE TITLE
[Feature Request]: Multiple PrintNode keys

### ISSUE THREAD

**Issue by invaders-xx** [rawilk/laravel-printing#30]
### Feature Description

Is there any way to handle multiple printnode keys in order to manage multiple printnode subscriptions ?

**Comment by rawilk** [comment]
You may switch them out at runtime like this:

```php
app(\Rawilk\Printing\Api\PrintNode\PrintNode::class)->setApiKey('your-new-key');
```

**Comment by invaders-xx** [comment]
Many thanks for your quick feedback. I will give it a try!
