### ISSUE TITLE
Content() dont work

### ISSUE THREAD

**Issue by Cahandar** [rawilk/laravel-printing#34]
### Laravel Printing Version

v3

### Laravel Version

v8

### Bug description

I can print pdf file but i want print text content() dont work .
$printerId = '71387975';

$text = (string) (new ReceiptPrinter)
            ->centerAlign()
            ->text('My heading')
            ->leftAlign()
            ->line()
            ->twoColumnText('Item 1', '2.00')
            ->twoColumnText('Item 2', '4.00')
            ->feed(2)
            ->centerAlign()
            ->barcode('1234')
            ->cut();
        
        Printing::newPrintTask()
            ->printer($printerId)
            ->content($text) 
            ->send();

### Steps to reproduce

.

### Relevant log output

```shell
.
```

**Comment by TahaYasin61** [comment]
Hello, I am having the same problem. Did you solve it?

**Comment by AlexPodaru** [comment]
When using content() method you can specify the content type with the 2nd parameter. Depending on your used driver you can find the available content types in Printing/Drivers/<your driver>/ContentType.php

Ex:
`
Printing::newPrintTask()
        ->printer($printerId)
        ->content($text, 'text/plain')
        ->send();
`
or in my case loading with a different name:
`
use Rawilk\Printing\Drivers\Cups\ContentType as PrintingCUPSContentType;
Printing::newPrintTask()
        ->printer($printerId)
        ->content($text, PrintingCUPSContentType::TEXT)
        ->send();
`

**Comment by rawilk** [comment]
I can't see anything from your code that would be preventing it from working. If your PrintNode account (if you're using that driver) is receiving the job, then it should be working properly.
