### ISSUE TITLE
Send name of job to CUPS - Resolved

### ISSUE THREAD

**Issue by gallomaf** [rawilk/laravel-printing#35]
### Laravel Printing Version

v3.0.0

### Laravel Version

v9.01

### Bug description

Hello! This package is wonderful :-) Thank you.

I want to ask one question. I'm using it with cups (installed on wsl2 on windows server of my customer).

I want to send name of the file with ->jobTitle() to the cups. 

The cups is not showing the name of the job.

How I could resolve?

Thank you

**Comment by gallomaf** [comment]
The problem is resolved by acting on server cups settings.

In  /etc/cups/cupsd.conf file we need to change all the lines 
`JobPrivateValues ​​default`
to `JobPrivateValues ​​none`

In this way, CUPS will show the user who send the job and the name of the job.

PS: The file could be changed also from web interface, from **Administration** > **Edit Configuration File**

**Comment by rawilk** [comment]
Thanks for the info. I'll update the docs to show that.
