### ISSUE TITLE
Wiki Not Accessible

### ISSUE THREAD

**Issue by ItsGageHolland** [rawilk/laravel-printing#5]
### Description

Wiki URL returning HTTP 500 Server Error

### Steps to reproduce

Multiple cross platform browser check & [httpstatus.io](https://httpstatus.io?url=https://randallwilk.dev/docs/laravel-printing)

**Context**
- Laravel Printing version: 1.2.2
- Laravel version: N/A

**Comment by rawilk** [comment]
Thanks for letting me know. It is back up now.
