### ISSUE TITLE
[Feature Request]: Doc Update with an example of Local IP Printer

### ISSUE THREAD

**Issue by hardiklakhalani** [rawilk/laravel-printing#66]
### Feature Description

I'm migrating from [charlieuki/receipt-printer](https://github.com/charlieuki/receipt-printer ) for Following Reasons:
- Not able to print custom text
- Too Tied with the non dynamic format
- Not compliant with new php version

Now the question is what would be the configuration for [rawilk/laravel-printing ](https://github.com/rawilk/laravel-printing )if I have a _Local_ printer as follows:

```php
connector_type: "network",
connector_discriptor: "192.168.2.248",
port: 9100
```
Code given above worked in [charlieuki/receipt-printer](https://github.com/charlieuki/receipt-printer )
But not sure how to use this info in `this` package
I've tried so many snippets from the existing doc but none of them shows what config it requires.

### Is this feature valuable for other users as well and why?

Yes, it's definitely valuable to others as there are very very less information & Laravel packages on the web for POS Printing, And only this package looks promising.

**Comment by danielfaulknor** [comment]
You need to use PrintNode or CUPS. If you are on a Linux server, you can install CUPS locally and add your printer to that
