### ISSUE TITLE
Dynamic printer_node_api key not Updated From V-3.0.0

### ISSUE THREAD

**Issue by hasi94** [rawilk/laravel-printing#76]
### Laravel Printing Version

v3.0.0

### Laravel Version

v8.0

### Print Driver

PrinterNode

### Bug description

set the printer_node_api_key from controller  dynamically 
`Config::set('printing.drivers.printnode.key', 'my-printer-node-key');`
it showing API key is  missing in  response here is  my code 
after that i downgrad to v2.0.0 and  it works fine
```
use \Rawilk\Printing\PrintTask;
use \Rawilk\Printing\Receipts\ReceiptPrinter;

public function xprinter(Request $request)
{
Config::set('printing.drivers.printnode.key', 'my-printer-node-key');
    try {
        $text = (string) (new ReceiptPrinter)
        ->centerAlign()
        ->text('My heading')
        ->leftAlign()
        ->line()
        ->twoColumnText('Item 1', '2.00')
        ->twoColumnText('Item 2', '4.00')
        ->feed(2)
        ->centerAlign()
        ->barcode('1234')
        ->cut();

        $printJob= new PrintTask;
        $printJob->printer("printer_id");
        $printJob->content($text);
        $printJob->send();
    } catch(Exception $e) {
        echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
    }
}
```

### Relevant log output

```shell
API key Missing
```

**Comment by rawilk** [comment]
That's probably because I inject the api key into the PrintNode api service class from the service provider. The service class is a singleton though, and there is a setter on it to update the api key.

All you need to do is set it like this:

```php
app(\Rawilk\Printing\Api\PrintNode\PrintNode::class)->setApiKey('your-new-key');
```

For more info, see: https://randallwilk.dev/docs/laravel-printing/v3/advanced-usage/printnode-api#user-content-introduction

**Comment by rawilk** [comment]
I'm going to close this issue for now since there hasn't been any activity on it for a while, and the issue described is possible to actually do with how I described above. Feel free to re-open in the future if necessary.
