### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Bonbooonn** [rawilk/laravel-printing#77]
### Feature Description

Is there a way to add a QR code to the receipt printer?

**Comment by rawilk** [comment]
I'm not 100% sure as I've never tried to print a QR code using a receipt printer myself. The `ReceiptPrinter` class wraps the `Printer` class from https://github.com/mike42/escpos-php, and forwards most method calls to it, so if it's possible with that class you should be able to do it; you just might need to dig around that source a little bit.

**Comment by rawilk** [comment]
I'm going to close this issue for now since it hasn't received any new activity on it. Feel free to re-open in the future if necessary.
