### ISSUE TITLE
Interface 'Psr\Http\Client\ClientInterface' not found

### ISSUE THREAD

**Issue by avido** [rawilk/laravel-printing#8]
### Description
PSR Client interface not found  (vendor/php-http/httplug/src/HttpClient.php:13)

### Steps to reproduce
- Fresh install laravel 8
- Install laravel-printing
- Add sample route:
```php
Route::get('/printers', function() {
    $printers = \Rawilk\Printing\Facades\Printing::printers();
    ddd($printers);
});
```

**Comment by Usa89** [comment]
HI, is this issue resolved. I am still getting this error:

```
$ % php artisan tinkerPsy Shell v0.10.5 (PHP 7.4.13 — cli) by Justin Hileman
>>> $printers = Printing::printers();
PHP Error:  Interface 'Psr\Http\Client\ClientInterface' not found in <path>/vendor/php-http/httplug/src/HttpClient.php on line 13
```

**Comment by stzoran1** [comment]
Same here, I got this error today.

**Comment by iamniels** [comment]
Fixed in this pull request: https://github.com/rawilk/laravel-printing/pull/14

**Comment by jayg0sai** [comment]
for that please check for http-client folder in your psr folder if not exist then install it first
