### ISSUE TITLE
[Feature Request]: Support for Laravel 11.x

### ISSUE THREAD

**Issue by demianottema** [rawilk/laravel-printing#82]
### Feature Description

I know Laravel 11.x is not out yet, but we can install it already.
I don't see any issues, so i will submit a PR to allow version 11.x for illuminate/support

**Comment by demianottema** [comment]
See #83

**Comment by rawilk** [comment]
v3.0.4 adds support for Laravel 11.x and php 8.3. I would've merged your PR, however I looked at the PR from shift first, which did the same thing.
